[platformio]
src_dir = ESP32_Bio_GPS_MPU_Sound_System

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library@^1.1.2
    mikalhart/TinyGPSPlus@^1.0.3
